/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.awt.Color;

/**
 *
 * @author mrles
 */
public class ViewRegister extends javax.swing.JFrame {

    /**
     * Creates new form ViewHome
     */
    public ViewRegister() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Txt_TelefonoMovil = new javax.swing.JTextField();
        Txt_cedula = new javax.swing.JTextField();
        Txt_Nombre = new javax.swing.JTextField();
        Txt_Apellidos = new javax.swing.JTextField();
        Txt_TelefonoFijo = new javax.swing.JTextField();
        ErrorMessage = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Txt_placa = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Txt_Tipo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Txt_Marca = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btn_History = new javax.swing.JButton();
        btn_Home = new javax.swing.JButton();
        btn_NewRegister = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PARQUEADERO APP");
        setName(""); // NOI18N

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("NUEVO REGISTRO");
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 1250, 50));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("TELEFONO MOVIL");
        bg.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 180, 30));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("CEDULA");
        bg.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 180, 30));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("NOMBRE");
        bg.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 180, 30));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("APELLIDOS");
        bg.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 180, 30));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("TELEFONO FIJO");
        bg.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 180, 30));

        Txt_TelefonoMovil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_TelefonoMovilActionPerformed(evt);
            }
        });
        bg.add(Txt_TelefonoMovil, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 300, 30));

        Txt_cedula.setToolTipText("");
        Txt_cedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_cedulaActionPerformed(evt);
            }
        });
        bg.add(Txt_cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 300, 30));

        Txt_Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_NombreActionPerformed(evt);
            }
        });
        bg.add(Txt_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 300, 30));

        Txt_Apellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_ApellidosActionPerformed(evt);
            }
        });
        bg.add(Txt_Apellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 300, 30));

        Txt_TelefonoFijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_TelefonoFijoActionPerformed(evt);
            }
        });
        bg.add(Txt_TelefonoFijo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, 300, 30));

        ErrorMessage.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        ErrorMessage.setForeground(new java.awt.Color(204, 0, 51));
        ErrorMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bg.add(ErrorMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 1120, 110));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("PLACA");
        bg.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 90, 180, 30));

        Txt_placa.setToolTipText("");
        Txt_placa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_placaActionPerformed(evt);
            }
        });
        bg.add(Txt_placa, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 90, 300, 30));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("TIPO");
        bg.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 130, 180, 30));

        Txt_Tipo.setToolTipText("");
        Txt_Tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_TipoActionPerformed(evt);
            }
        });
        bg.add(Txt_Tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 130, 300, 30));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("MARCA");
        bg.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 170, 180, 30));

        Txt_Marca.setToolTipText("");
        Txt_Marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_MarcaActionPerformed(evt);
            }
        });
        bg.add(Txt_Marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 170, 300, 30));

        jPanel2.setBackground(new java.awt.Color(51, 51, 255));

        btn_History.setBackground(new java.awt.Color(102, 204, 255));
        btn_History.setFont(new java.awt.Font("Arial", 0, 3)); // NOI18N
        btn_History.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/history.png"))); // NOI18N

        btn_Home.setBackground(new java.awt.Color(102, 204, 255));
        btn_Home.setFont(new java.awt.Font("Arial", 0, 3)); // NOI18N
        btn_Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/home.png"))); // NOI18N
        btn_Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HomeActionPerformed(evt);
            }
        });

        btn_NewRegister.setBackground(new java.awt.Color(102, 204, 255));
        btn_NewRegister.setFont(new java.awt.Font("Arial", 0, 3)); // NOI18N
        btn_NewRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/add.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_NewRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Home, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_History, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addComponent(btn_Home, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_NewRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_History, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(272, Short.MAX_VALUE))
        );

        bg.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 720));

        btnRegistrar.setBackground(new java.awt.Color(0, 0, 255));
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("GUARDAR");
        bg.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 240, 190, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Txt_TelefonoMovilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_TelefonoMovilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_TelefonoMovilActionPerformed

    private void Txt_cedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_cedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_cedulaActionPerformed

    private void Txt_NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_NombreActionPerformed

    private void Txt_ApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_ApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_ApellidosActionPerformed

    private void Txt_TelefonoFijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_TelefonoFijoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_TelefonoFijoActionPerformed

    private void Txt_placaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_placaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_placaActionPerformed

    private void Txt_TipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_TipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_TipoActionPerformed

    private void Txt_MarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_MarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_MarcaActionPerformed

    private void btn_HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_HomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewRegister().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel ErrorMessage;
    public javax.swing.JTextField Txt_Apellidos;
    public javax.swing.JTextField Txt_Marca;
    public javax.swing.JTextField Txt_Nombre;
    public javax.swing.JTextField Txt_TelefonoFijo;
    public javax.swing.JTextField Txt_TelefonoMovil;
    public javax.swing.JTextField Txt_Tipo;
    public javax.swing.JTextField Txt_cedula;
    public javax.swing.JTextField Txt_placa;
    private javax.swing.JPanel bg;
    public javax.swing.JButton btnRegistrar;
    public javax.swing.JButton btn_History;
    public javax.swing.JButton btn_Home;
    public javax.swing.JButton btn_NewRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
