/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.awt.Color;

/**
 *
 * @author mrles
 */
public class ViewRegister extends javax.swing.JFrame {

    /**
     * Creates new form ViewHome
     */
    public ViewRegister() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        BtnHome = new javax.swing.JPanel();
        LblHome = new javax.swing.JLabel();
        BtnFactura = new javax.swing.JPanel();
        LblFactura = new javax.swing.JLabel();
        BtnHistory = new javax.swing.JPanel();
        LblHistory = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Txt_TelefonoMovil = new javax.swing.JTextField();
        Txt_cedula = new javax.swing.JTextField();
        Txt_Nombre = new javax.swing.JTextField();
        Txt_Apellidos = new javax.swing.JTextField();
        Txt_TelefonoFijo = new javax.swing.JTextField();
        ErrorMessage = new javax.swing.JLabel();
        BtnGuardar = new javax.swing.JPanel();
        LblGuardar = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Txt_placa = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Txt_Tipo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Txt_Marca = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PARQUEADERO APP");
        setName(""); // NOI18N

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));

        BtnHome.setBackground(new java.awt.Color(255, 255, 255));

        LblHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/home.png"))); // NOI18N
        LblHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LblHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LblHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LblHomeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout BtnHomeLayout = new javax.swing.GroupLayout(BtnHome);
        BtnHome.setLayout(BtnHomeLayout);
        BtnHomeLayout.setHorizontalGroup(
            BtnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LblHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        BtnHomeLayout.setVerticalGroup(
            BtnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LblHome, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        );

        BtnFactura.setBackground(new java.awt.Color(255, 255, 255));

        LblFactura.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblFactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/home.png"))); // NOI18N
        LblFactura.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LblFactura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LblFacturaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LblFacturaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout BtnFacturaLayout = new javax.swing.GroupLayout(BtnFactura);
        BtnFactura.setLayout(BtnFacturaLayout);
        BtnFacturaLayout.setHorizontalGroup(
            BtnFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LblFactura, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
        );
        BtnFacturaLayout.setVerticalGroup(
            BtnFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LblFactura, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        );

        BtnHistory.setBackground(new java.awt.Color(255, 255, 255));

        LblHistory.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblHistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/home.png"))); // NOI18N
        LblHistory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LblHistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LblHistoryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LblHistoryMouseExited(evt);
            }
        });

        javax.swing.GroupLayout BtnHistoryLayout = new javax.swing.GroupLayout(BtnHistory);
        BtnHistory.setLayout(BtnHistoryLayout);
        BtnHistoryLayout.setHorizontalGroup(
            BtnHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LblHistory, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
        );
        BtnHistoryLayout.setVerticalGroup(
            BtnHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LblHistory, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnFactura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnHistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(BtnHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnHistory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 720));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("NUEVO REGISTRO");
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 1250, 50));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("TELEFONO MOVIL");
        bg.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 180, 30));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("CEDULA");
        bg.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 180, 30));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setText("NOMBRE");
        bg.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 180, 30));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setText("APELLIDOS");
        bg.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 180, 30));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setText("TELEFONO FIJO");
        bg.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 180, 30));

        Txt_TelefonoMovil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_TelefonoMovilActionPerformed(evt);
            }
        });
        bg.add(Txt_TelefonoMovil, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 300, 30));

        Txt_cedula.setToolTipText("");
        Txt_cedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_cedulaActionPerformed(evt);
            }
        });
        bg.add(Txt_cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 300, 30));

        Txt_Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_NombreActionPerformed(evt);
            }
        });
        bg.add(Txt_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 300, 30));

        Txt_Apellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_ApellidosActionPerformed(evt);
            }
        });
        bg.add(Txt_Apellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 300, 30));

        Txt_TelefonoFijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_TelefonoFijoActionPerformed(evt);
            }
        });
        bg.add(Txt_TelefonoFijo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 300, 30));

        ErrorMessage.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        ErrorMessage.setForeground(new java.awt.Color(204, 0, 51));
        ErrorMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bg.add(ErrorMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 1120, 110));

        BtnGuardar.setBackground(new java.awt.Color(0, 0, 153));

        LblGuardar.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        LblGuardar.setForeground(new java.awt.Color(255, 255, 255));
        LblGuardar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblGuardar.setText("GUARDAR");
        LblGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LblGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblGuardarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LblGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LblGuardarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout BtnGuardarLayout = new javax.swing.GroupLayout(BtnGuardar);
        BtnGuardar.setLayout(BtnGuardarLayout);
        BtnGuardarLayout.setHorizontalGroup(
            BtnGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LblGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        BtnGuardarLayout.setVerticalGroup(
            BtnGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LblGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        );

        bg.add(BtnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 240, 320, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setText("PLACA");
        bg.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 90, 180, 30));

        Txt_placa.setToolTipText("");
        Txt_placa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_placaActionPerformed(evt);
            }
        });
        bg.add(Txt_placa, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 90, 300, 30));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel9.setText("TIPO");
        bg.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 130, 180, 30));

        Txt_Tipo.setToolTipText("");
        Txt_Tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_TipoActionPerformed(evt);
            }
        });
        bg.add(Txt_Tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 130, 300, 30));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel10.setText("MARCA");
        bg.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 170, 180, 30));

        Txt_Marca.setToolTipText("");
        Txt_Marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_MarcaActionPerformed(evt);
            }
        });
        bg.add(Txt_Marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 170, 300, 30));

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        bg.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LblHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblHomeMouseEntered
        BtnHome.setBackground(Color.CYAN);
    }//GEN-LAST:event_LblHomeMouseEntered

    private void LblHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblHomeMouseExited
        BtnHome.setBackground(Color.WHITE);
    }//GEN-LAST:event_LblHomeMouseExited

    private void LblFacturaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblFacturaMouseEntered
        BtnFactura.setBackground(Color.CYAN);
    }//GEN-LAST:event_LblFacturaMouseEntered

    private void LblFacturaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblFacturaMouseExited
        BtnFactura.setBackground(Color.WHITE);
    }//GEN-LAST:event_LblFacturaMouseExited

    private void LblHistoryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblHistoryMouseEntered
        BtnHistory.setBackground(Color.CYAN);
    }//GEN-LAST:event_LblHistoryMouseEntered

    private void LblHistoryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblHistoryMouseExited
        BtnHistory.setBackground(Color.WHITE);
    }//GEN-LAST:event_LblHistoryMouseExited

    private void Txt_TelefonoMovilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_TelefonoMovilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_TelefonoMovilActionPerformed

    private void Txt_cedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_cedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_cedulaActionPerformed

    private void Txt_NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_NombreActionPerformed

    private void Txt_ApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_ApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_ApellidosActionPerformed

    private void Txt_TelefonoFijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_TelefonoFijoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_TelefonoFijoActionPerformed

    private void LblGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblGuardarMouseEntered
        BtnGuardar.setBackground(Color.CYAN);
        LblGuardar.setForeground(Color.BLACK);
    }//GEN-LAST:event_LblGuardarMouseEntered

    private void LblGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblGuardarMouseExited
        BtnGuardar.setBackground(Color.BLUE);
        LblGuardar.setForeground(Color.WHITE);
    }//GEN-LAST:event_LblGuardarMouseExited

    private void Txt_placaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_placaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_placaActionPerformed

    private void Txt_TipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_TipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_TipoActionPerformed

    private void Txt_MarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_MarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_MarcaActionPerformed

    private void LblGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblGuardarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_LblGuardarMouseClicked

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewRegister().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BtnFactura;
    public javax.swing.JPanel BtnGuardar;
    private javax.swing.JPanel BtnHistory;
    private javax.swing.JPanel BtnHome;
    public javax.swing.JLabel ErrorMessage;
    private javax.swing.JLabel LblFactura;
    public javax.swing.JLabel LblGuardar;
    private javax.swing.JLabel LblHistory;
    private javax.swing.JLabel LblHome;
    public javax.swing.JTextField Txt_Apellidos;
    public javax.swing.JTextField Txt_Marca;
    public javax.swing.JTextField Txt_Nombre;
    public javax.swing.JTextField Txt_TelefonoFijo;
    public javax.swing.JTextField Txt_TelefonoMovil;
    public javax.swing.JTextField Txt_Tipo;
    public javax.swing.JTextField Txt_cedula;
    public javax.swing.JTextField Txt_placa;
    private javax.swing.JPanel bg;
    public javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
